### ISSUE TITLE
GraphQL Error when running gatsby develop

### ISSUE THREAD

**Issue by tamarahills** [mozilla/concepts#97]
I'm getting an error when running `gatsby develop` and trying to hit a localhost url such as `localhost:8000/vpn/index` or `localhost:8000/scroll/v1a` (I also tried a few others and tried trailing slashes as I saw few issues about that).

Error I'm getting is error GraphQL Error Field "image" must not have a selection since type "String" has no subfields.

See below for full output on console.

Tamaras-MacBook-Pro:concepts mozilla$ gatsby develop
success open and validate gatsby-configs — 0.006 s
success load plugins — 0.488 s
success onPreInit — 0.009 s
success initialize cache — 0.018 s
success copy gatsby files — 0.099 s
success onPreBootstrap — 0.006 s
success source and transform nodes — 0.102 s
success building schema — 0.225 s
success createPages — 0.067 s
success createPagesStatefully — 0.032 s
success onPreExtractQueries — 0.000 s
success update schema — 0.018 s
error GraphQL Error Field "image" must not have a selection since type "String" has no subfields.

  file: /Volumes/development/concepts/src/templates/conceptVariant/index.js

  12 |         metaSecondaryLink
  13 |         concept {
  14 |           cobrand
  15 |           cobrandIcon {
  16 |             publicURL
  17 |           }
  18 |           hero {
  19 |             title
  20 |             text
  21 |             cta
> 22 |             image {
     |                   ^
  23 |               publicURL
  24 |             }
  25 |           }
  26 |           facets {
  27 |             title
  28 |             text
  29 |             image {
  30 |               publicURL
  31 |             }
  32 |           }

success extract queries from components — 0.055 s
⠁ (node:37760) DeprecationWarning: Passing lineNumber and colNumber is deprecated to @babel/code-frame. Please use `codeFrameColumns`.
success run graphql queries — 0.029 s — 20/20 733.15 queries/second
success write out page data — 0.009 s
success write out redirect data — 0.001 s
⠐ onPostBootstrapdone generating icons for manifest
success onPostBootstrap — 0.553 s

info bootstrap finished - 4.579709867 s

 DONE  Compiled successfully in 3833ms                               11:20:21 AM

You can now view fx-concepts in the browser.

  http://localhost:8000/

View GraphiQL, an in-browser IDE, to explore your site's data and schema

  http://localhost:8000/___graphql

Note that the development build is not optimized.
To create a production build, use npm run build

ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.

**Comment by johngruen** [comment]
i think i know what's happening...will investigate monday

**Comment by johngruen** [comment]
hmm...i can't repro the issue unfortunately...

**Comment by tamarahills** [comment]
Do you think it can have something to do with the relative image path?  I was googling around a bit and found this blog:  [https://theleakycauldronblog.com/blog/problems-with-gatsby-image-and-their-workarounds/]().  They talk about using `gatsby-remark-relative-images` to convert image src(s) in markdown to be relative to their node's parent directory. 

I don't have any experience with GraphQL or gatsby, so any pointers appreciated in getting this running.  Thanks.

**Comment by tamarahills** [comment]
This mysteriously went away after I deleted the directory and reinstalled everything.

**Comment by johngruen** [comment]
@tamarahills sorry i didn't get back to you on this earlier...after building this thing we decided gatsby is more trouble than its worth. At some point we might just rewrite this thing as a good old Jekyll site to avoid weird hiccups like this.
